# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CdkXHzs4EUJ_yg2WDr8NGLuOwTxsgvy7
"""

# 1. Linear Search (Doğrusal Arama) - Herkese tek tek bakar
def linear_search(liste, hedef):
    for i in range(len(liste)):
        if liste[i] == hedef:
            return i
    return -1

# 2. Binary Search (İkili Arama) - Ortadan bölerek bakar (Liste sıralı olmalı!)
def binary_search(liste, hedef):
    dusuk = 0
    yuksek = len(liste) - 1
    while dusuk <= yuksek:
        orta = (dusuk + yuksek) // 2
        if liste[orta] == hedef:
            return orta
        elif liste[orta] < hedef:
            dusuk = orta + 1
        else:
            yuksek = orta - 1
    return -1

# 1. Bubble Sort (Kabarcık Sıralama) - En büyüğü sona atar
def bubble_sort(liste):
    n = len(liste)
    for i in range(n):
        for j in range(0, n-i-1):
            if liste[j] > liste[j+1]:
                liste[j], liste[j+1] = liste[j+1], liste[j]
    return liste

# 2. Selection Sort (Seçmeli Sıralama) - En küçüğü bulup başa koyar
def selection_sort(liste):
    for i in range(len(liste)):
        en_kucuk = i
        for j in range(i+1, len(liste)):
            if liste[j] < liste[en_kucuk]:
                en_kucuk = j
        liste[i], liste[en_kucuk] = liste[en_kucuk], liste[i]
    return liste

# 3. Insertion Sort (Araya Ekleme) - Kart destesi dizer gibi
def insertion_sort(liste):
    for i in range(1, len(liste)):
        anahtar = liste[i]
        j = i-1
        while j >= 0 and anahtar < liste[j]:
            liste[j+1] = liste[j]
            j -= 1
        liste[j+1] = anahtar
    return liste

# 4. Quick Sort (Hızlı Sıralama) - Bir pivot seçer, etrafında toplar
def quick_sort(liste):
    if len(liste) <= 1:
        return liste
    pivot = liste[len(liste) // 2]
    sol = [x for x in liste if x < pivot]
    orta = [x for x in liste if x == pivot]
    sag = [x for x in liste if x > pivot]
    return quick_sort(sol) + orta + quick_sort(sag)